--Inserting into tables
INSERT INTO OSOBY(IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES();

INSERT INTO WYCIECZKI(NAZWA, KRAJ, DATA, OPIS, LICZBA_MIEJSC)
VALUES();

INSERT INTO REZERWACJE (ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES();