--Uczestnik wycieczki
CREATE OR REPLACE TYPE UCZESTNIK_WYCIECZKI AS OBJECT
(
    NAZWA VARCHAR2(100),
    KRAJ VARCHAR2(50),
    "DATA" DATE,
    IMIE VARCHAR2(50),
    NAZWISKO VARCHAR2(50),
    STATUS CHAR(1)
);

CREATE OR REPLACE TYPE UCZESTNICY_WYCIECZKI_TABELA IS TABLE OF UCZESTNIK_WYCIECZKI;

--Wycieczka
CREATE OR REPLACE TYPE WYCIECZKA AS OBJECT
(
    NAZWA VARCHAR2(100),
    KRAJ VARCHAR2(50),
    "DATA" DATE,
    OPIS VARCHAR2(200),
    LICZBA_MIEJSC INT
);

CREATE OR REPLACE TYPE WYCIECZKI_TABELA IS TABLE OF WYCIECZKA;
